### ISSUE TITLE
reload fails on safari

### ISSUE THREAD

**Issue by cysouw** [digitallinguists/msa-editor#12]
Safari does not reload the file. If this is a problem in Safari, then no workaround is necessary. We'll use chrome :-)

**Comment by FrankNagel** [comment]
I have to close this issue without a fix. There seems to be no workaround for Safari except going through the 'Choose File' dialog. Chrome or Firefox work fine.

When you change a file from outside the browser between initial load and reload, the inode number changes on OS X. Safari seems to try to open the file by inode number and not using the name.

I implemented some user feedback when reloading fails.
